import React, { useState } from 'react'
import { useChordPanel } from '../../contexts/ChordPanelContext'
import ChordTooltip from './ChordTooltip'
import './ProgressionBuilder.css'

const ProgressionBuilder = ({ scaleData }) => {
  const { selectedChords } = useChordPanel()
  const [progressionLines, setProgressionLines] = useState([[]])
  const [currentLine, setCurrentLine] = useState(0)

  const addChord = (chord) => {
    setProgressionLines(prev => {
      const newLines = [...prev]
      newLines[currentLine] = [...newLines[currentLine], chord]
      return newLines
    })
  }

  const removeChord = (lineIndex, chordIndex) => {
    setProgressionLines(prev => {
      const newLines = [...prev]
      newLines[lineIndex] = newLines[lineIndex].filter((_, index) => index !== chordIndex)
      return newLines
    })
  }

  const addNewLine = () => {
    setProgressionLines(prev => [...prev, []])
    setCurrentLine(progressionLines.length)
  }

  const removeLine = (lineIndex) => {
    if (progressionLines.length > 1) {
      setProgressionLines(prev => prev.filter((_, index) => index !== lineIndex))
      if (currentLine >= progressionLines.length - 1) {
        setCurrentLine(Math.max(0, progressionLines.length - 2))
      }
    }
  }

  const clearAll = () => {
    setProgressionLines([[]])
    setCurrentLine(0)
  }

  const exportToPDF = () => {
    // Create a formatted string of the progression
    const progressionText = progressionLines
      .map((line, index) => `Line ${index + 1}: ${line.join(' - ') || '(empty)'}`)
      .join('\n')

    // For now, we'll use the browser's print functionality
    // In a real app, you'd use a PDF library like jsPDF or react-pdf
    const printWindow = window.open('', '_blank')
    printWindow.document.write(`
      <html>
        <head>
          <title>Chord Progression</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            h1 { color: #333; }
            .line { margin: 10px 0; padding: 10px; background: #f5f5f5; border-radius: 5px; }
            .chord { display: inline-block; margin: 5px; padding: 5px 10px; background: white; border-radius: 3px; border: 1px solid #ddd; }
          </style>
        </head>
        <body>
          <h1>Chord Progression</h1>
          ${progressionLines.map((line, index) => 
            `<div class="line">
              <strong>Line ${index + 1}:</strong><br>
              ${line.map(chord => `<span class="chord">${chord}</span>`).join(' ')}
              ${line.length === 0 ? '<em>(empty)</em>' : ''}
            </div>`
          ).join('')}
          <p><small>Generated by Strubloid Music Theory</small></p>
        </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.print()
  }

  // Get seventh notes from scale data
  const seventhNotes = scaleData?.chord_sevenths ? 
    scaleData.chord_sevenths.map(item => item.seventh) : 
    ['C7', 'D7', 'E7', 'F7', 'G7', 'A7', 'B7'] // fallback

  return (
    <div className="progression-builder-panel">
      <div className="panel-header">
        <h3 className="panel-title">Building Progressions</h3>
        <div className="panel-actions">
          <button className="export-button" onClick={exportToPDF}>
            📄 Export PDF
          </button>
          <button className="clear-button" onClick={clearAll}>
            Clear All
          </button>
        </div>
      </div>

      {/* Selected Chords from Main Panel */}
      {selectedChords.length > 0 && (
        <div className="selected-chords-section">
          <h4 className="section-title">From Selected Chords:</h4>
          <div className="quick-chords-grid">
            {[...new Set(selectedChords)].map((chord, index) => (
              <ChordTooltip key={index} chord={chord}>
                <button
                  className="quick-chord-button selected"
                  onClick={() => addChord(chord)}
                >
                  {chord}
                </button>
              </ChordTooltip>
            ))}
          </div>
        </div>
      )}

      {/* Seventh Notes Selection */}
      <div className="seventh-notes-section">
        <h4 className="section-title">Seventh Notes:</h4>
        <div className="quick-chords-grid">
          {seventhNotes.map((chord, index) => (
            <ChordTooltip key={index} chord={chord}>
              <button
                className="seventh-chord-button"
                onClick={() => addChord(chord)}
              >
                {chord}
              </button>
            </ChordTooltip>
          ))}
        </div>
      </div>

      {/* Progression Lines */}
      <div className="progression-section">
        <div className="progression-header">
          <h4 className="section-title">Progression:</h4>
          <button className="add-line-button" onClick={addNewLine}>
            ➕ New Line
          </button>
        </div>

        <div className="progression-lines">
          {progressionLines.map((line, lineIndex) => (
            <div
              key={lineIndex}
              className={`progression-line ${currentLine === lineIndex ? 'active' : ''}`}
            >
              <div className="line-header">
                <span className="line-number">Line {lineIndex + 1}</span>
                <button
                  className="line-select-button"
                  onClick={() => setCurrentLine(lineIndex)}
                  title="Select this line for adding chords"
                >
                  {currentLine === lineIndex ? '✓' : '○'}
                </button>
                {progressionLines.length > 1 && (
                  <button
                    className="remove-line-button"
                    onClick={() => removeLine(lineIndex)}
                    title="Remove this line"
                  >
                    ×
                  </button>
                )}
              </div>

              <div className="line-chords">
                {line.length === 0 ? (
                  <div className="empty-line">
                    {currentLine === lineIndex ? 'Add chords here...' : '(empty)'}
                  </div>
                ) : (
                  line.map((chord, chordIndex) => (
                    <div key={chordIndex} className="progression-chord-item">
                      <ChordTooltip chord={chord}>
                        <div className="chord-display">{chord}</div>
                      </ChordTooltip>
                      <button
                        className="remove-chord-button"
                        onClick={() => removeChord(lineIndex, chordIndex)}
                        title="Remove chord"
                      >
                        ×
                      </button>
                    </div>
                  ))
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="progression-info">
        <span className="progression-stats">
          {progressionLines.length} line{progressionLines.length !== 1 ? 's' : ''}, {' '}
          {progressionLines.reduce((total, line) => total + line.length, 0)} chord{progressionLines.reduce((total, line) => total + line.length, 0) !== 1 ? 's' : ''} total
        </span>
      </div>
    </div>
  )
}

export default ProgressionBuilder