import React, { useState } from 'react'
import { useChordPanel } from '../../contexts/ChordPanelContext'
import ChordTooltip from './ChordTooltip'
import InlineChordDisplay from './InlineChordDisplay'
import './ProgressionBuilder.css'

const ProgressionBuilder = ({ scaleData }) => {
  const { 
    progressionLines, 
    currentLine, 
    addChordToProgression, 
    removeChordFromProgression, 
    addProgressionLine, 
    removeProgressionLine, 
    clearProgression, 
    setCurrentProgressionLine,
    showChords
  } = useChordPanel()
  


  const addChord = (chord) => {
    addChordToProgression(chord)
  }

  const removeChord = (lineIndex, chordIndex) => {
    removeChordFromProgression(lineIndex, chordIndex)
  }

  const addNewLine = () => {
    addProgressionLine()
  }

  const removeLine = (lineIndex) => {
    removeProgressionLine(lineIndex)
  }

  const clearAll = () => {
    clearProgression()
  }

  const exportToPDF = () => {
    // Create a formatted string of the progression
    const progressionText = progressionLines
      .map((line, index) => `Line ${index + 1}: ${line.join(' - ') || '(empty)'}`)
      .join('\n')

    // For now, we'll use the browser's print functionality
    // In a real app, you'd use a PDF library like jsPDF or react-pdf
    const printWindow = window.open('', '_blank')
    printWindow.document.write(`
      <html>
        <head>
          <title>Chord Progression</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            h1 { color: #333; }
            .line { margin: 10px 0; padding: 10px; background: #f5f5f5; border-radius: 5px; }
            .chord { display: inline-block; margin: 5px; padding: 5px 10px; background: white; border-radius: 3px; border: 1px solid #ddd; }
          </style>
        </head>
        <body>
          <h1>Chord Progression</h1>
          ${progressionLines.map((line, index) => 
            `<div class="line">
              <strong>Line ${index + 1}:</strong><br>
              ${line.map(chord => `<span class="chord">${chord}</span>`).join(' ')}
              ${line.length === 0 ? '<em>(empty)</em>' : ''}
            </div>`
          ).join('')}
          <p><small>Generated by Strubloid Music Theory</small></p>
        </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.print()
  }

  return (
    <div className="progression-builder-panel">
      <div className="panel-header">
        <h3 className="panel-title">Building Progressions</h3>
        <div className="panel-actions">
          <button className="export-button" onClick={exportToPDF}>
            📄 Export PDF
          </button>
          <button className="clear-button" onClick={clearAll}>
            Clear All
          </button>
        </div>
      </div>

      {/* Scale Chords and Seventh Notes */}
      <div className="chord-selection-grid">
        <div className="scale-chords-section">
          <h4 className="section-title">Scale Chords:</h4>
          <div className="compact-chords-grid">
            {scaleData?.scale_degrees?.map((degree, index) => (
              <button
                key={index}
                className="compact-chord-button"
                onClick={() => addChord(degree.chord)}
                title={`${degree.roman} - ${degree.chord}`}
              >
                {degree.chord}
              </button>
            ))}
          </div>
        </div>
        
        <div className="seventh-notes-section">
          <h4 className="section-title">Seventh Notes:</h4>
          <div className="compact-chords-grid">
            {scaleData?.chord_sevenths?.map((seventhData, index) => (
              <button
                key={index}
                className="compact-seventh-button"
                onClick={() => addChord(seventhData.seventh)}
                title={`Resolves to ${seventhData.resolves_to}`}
              >
                {seventhData.seventh}
              </button>
            ))}
          </div>
        </div>
      </div>


      <div className="progression-section">
        <div className="progression-header">
          <h4 className="section-title">Progression:</h4>
          <button className="add-line-button" onClick={addNewLine}>
            ➕ New Line
          </button>
        </div>

        <div className="progression-lines">
          {progressionLines.map((line, lineIndex) => (
            <div
              key={lineIndex}
              className={`progression-line ${currentLine === lineIndex ? 'active' : ''}`}
            >
              <div className="line-header">
                <span className="line-number">Line {lineIndex + 1}</span>
                <button
                  className="line-select-button"
                  onClick={() => setCurrentProgressionLine(lineIndex)}
                  title="Select this line for adding chords"
                >
                  {currentLine === lineIndex ? '✓' : '○'}
                </button>
                {progressionLines.length > 1 && (
                  <button
                    className="remove-line-button"
                    onClick={() => removeLine(lineIndex)}
                    title="Remove this line"
                  >
                    ×
                  </button>
                )}
              </div>

              <div className="line-chords">
                {line.length === 0 ? (
                  <div className="empty-line">
                    {currentLine === lineIndex ? 'Add chords here...' : '(empty)'}
                  </div>
                ) : (
                  line.map((chord, chordIndex) => (
                    <div key={chordIndex} className="progression-chord-item">
                      {showChords ? (
                        <div className="chord-with-diagram">
                          <div className="chord-diagram-inline">
                            <InlineChordDisplay chord={chord} />
                          </div>
                          <div className="chord-text-small">{chord}</div>
                          <button
                            className="remove-chord-button inline-mode"
                            onClick={() => removeChord(lineIndex, chordIndex)}
                            title="Remove chord"
                          >
                            ×
                          </button>
                        </div>
                      ) : (
                        <>
                          <ChordTooltip chord={chord}>
                            <div className="chord-display">
                              {chord}
                            </div>
                          </ChordTooltip>
                          <button
                            className="remove-chord-button"
                            onClick={() => removeChord(lineIndex, chordIndex)}
                            title="Remove chord"
                          >
                            ×
                          </button>
                        </>
                      )}
                    </div>
                  ))
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="progression-info">
        <span className="progression-stats">
          {(() => {
            const totalChords = progressionLines.reduce((total, line) => total + line.length, 0);
            return `${progressionLines.length} line${progressionLines.length !== 1 ? 's' : ''}, ${totalChords} chord${totalChords !== 1 ? 's' : ''} total`;
          })()}
        </span>
      </div>
    </div>
  )
}

export default ProgressionBuilder